### ISSUE TITLE
Best practice for enqueue_scripts()

### ISSUE THREAD

**Issue by steveadamsfixedit** [cliffordp/cliff-wp-plugin-boilerplate#102]
I've used the boilerplate to create a custom plugin to track user engagement analytics on live streamed video assets. included in the plugin within the /public directory are some fairly robust JavaScripts that mesh with a webhook from the stream provider and a AJAX call to track real time player events. 
   It's my understanding that these scripts added to the enqueue_scripts() function in the public/class-plugin-name-public.php run on every single page in the rather vast WP site I'm intending to deploy it on. This seems inefficient and rather insecure...
   What's best practice as far as only getting the scripts to run on specific pages...for instance, making a custom theme template and only applying that template file to a page containing video assets?

**Comment by cliffordp** [comment]
Your comment doesn't even seem to apply to my repo (e.g. no `public` directory), and I noticed you posted the same to many other boilerplates (see below) so I'll consider this either an accident or spam and close it.

* https://github.com/wp-strap/wordpress-plugin-boilerplate/issues/1
* https://github.com/BoilWP/WordPress-Plugin-Boilerplate/issues/18
* https://github.com/GaryJones/plugin-boilerplate/issues/20
* https://github.com/JoeSz/WordPress-Plugin-Boilerplate-Tutorial/issues/18
* https://github.com/WPBP/WordPress-Plugin-Boilerplate-Powered/issues/186
