### ISSUE TITLE
Minify CSS and JS

### ISSUE THREAD

**Issue by cliffordp** [cliffordp/cliff-wp-plugin-boilerplate#20]

**Comment by cliffordp** [comment]
https://github.com/youknowriad/wp-js-plugin-starter has some nice info

**Comment by Stefan2409** [comment]
I'm working on this. The CSS part is already done via gulp. JS will follow.... The only thing I wanted to ask in advance is: if there's a feature branch related to this?

**Comment by cliffordp** [comment]
Hi, @Stefan2409. Thanks for your interest in contributing. I haven't started work on this yet. Let me know if I can be of any help along the way.
