### ISSUE TITLE
Consider moving from Parcel to Webpack

### ISSUE THREAD

**Issue by cliffordp** [cliffordp/cliff-wp-plugin-boilerplate#77]
We're already using Parcel (see #55), and it's working nicely, but WP uses Webpack so maybe we should, too:
* https://developer.wordpress.org/block-editor/tutorials/javascript/js-build-setup/
* https://github.com/gambitph/Stackable/blob/master/package.json
* https://github.com/WordPress/gutenberg/blob/master/package.json
* https://github.com/petehunt/webpack-howto

Let's build things via Weback to compare not only the ease of use but also the file size of the resulting built files.

**Comment by cliffordp** [comment]
After playing with this a long while, the answer is _'no'_... because:
* Parcel was working, _including HMR_, and is only going to improve overall with Parcel 2.
* The
* Extending [@wordpress/scripts](https://www.npmjs.com/package/@wordpress/scripts)' webpack was more setup code than Parcel's (added complexity) and didn't give us any benefits.
* wp/scripts' webpack says it's subject to change (which could be beneficial if we're just inheriting), but the granular integration steps makes our code more brittle.
* wp/scripts only packages _JS_ files, not JSX, PCSS, SASS, or even CSS files -- for concatenation, minification, etc.
* We can use wp/scripts' _scripts_ (e.g. linting and checking licenses) if we want to without needing to extend their webpack.
* WP + React + webpack just isn't giving us HMR without having to define the URI we're running on (lame) or wrap our code with things like `hot()` or import extra `<script>` in the entry file's header
* Each of our glob-added PostCSS files had an empty or near-empty `style.pcss.json` file generated alongside them, which is cruft. (Unsure which package/command was causing this, but it definitely seemed intentional.)

For reference, we gave it the full effort: https://github.com/cliffordp/cliff-wp-plugin-boilerplate/pull/80/files

**Comment by skorasaurus** [comment]
I came across this, thanks for sharing! I've been assessing different building tools/setups for creating Gutenberg blocks.

**Comment by cliffordp** [comment]
Hi, @skorasaurus 

Glad you found this. Let me know if there's anything I can do to help.

**Comment by cliffordp** [comment]
A neat little _enqueue_ trick I found along the way, if using WP's webpack: https://github.com/WordPress/gutenberg/issues/18471#issuecomment-556076890
