### ISSUE TITLE
Implement setup script

### ISSUE THREAD

**Issue by barryhughes** [cliffordp/cliff-wp-plugin-boilerplate#93]
The readme lists a number of areas in which a search and replace should be performed. I think it could be handy to have a script that guides users through this:

* Could be a standalone PHP script that can be executed using something like `./bin/setup` (ie, it would not depend on WP CLI nor would it be a Composer script)
* It could validate that the plugin slug (for example) is a valid slug before performing search-and-replace
* Could provide a final summary of the changes and a chance to bail out or make changes
* It could run `composer install` at the end

Conceptually, what do you think&mdash;worthwhile/maybe useful but not sure/meh?

**Comment by cliffordp** [comment]
Yes, sir! Please see #73

**Comment by barryhughes** [comment]
Hah! I promise I looked for an existing issue first of all ;-)
